---
title: "Selected Scientific Talks and Posters"
---

-   Truong MS. (2025) Talk: *Reply to Paul E. Meehl: Machine Learning Structural Equation Modeling and Falsificatory Data Analysis.* Presented at York University Quantitative Methods Forum. [Slides](pdf/QM_Forum_September_29_2025.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"}

    -   *Abstract*: Here, a three-manuscript dissertation is proposed. The unifying theme among these three manuscripts is the synthesis of Falsificatory Data Analysis (FDA) and Machine Learning Structural Equation Modeling (ML-SEM), primarily as a means to assess and improve data quality. There exists a tension between the over-fitting inherent to the method of ML-SEM and the default belief that the null hypothesis is always false. The overall research question guiding this dissertation is whether a new methodology, FDA, can help motivate the productive use of ML-SEM. To answer this research question, three separate manuscripts are proposed. The first manuscript proposes the concept of FDA as an elaboration of the original confirmatory and exploratory data analysis distinction, then performs a logical analysis on the merits of the proposed concept. The second manuscript builds on the ML-SEM technique of SEM trees by researching the use of Integrated Generalised Structured Component Analysis (IGSCA) in SEM trees, as opposed to the traditional covariance-based SEM. This method of using IGSCA for SEM trees is named IGSCA trees. The third and final manuscript will demonstrate the scientific utility of synergizing FDA methodology with the method of ML-SEM in a ‘Tutorial’ style manuscript applied to various data analytical problems. The expected impact of this dissertation is a new elaboration of Tukey’s original distinction between exploratory and confirmatory data analysis; the introduction of a new variant of SEM trees; and a demonstration of how the two may be productively synergized.

-   Truong MS., Zhang, X., & Flora, DB. (2025) Talk: *What Happens When Sample Size is the Confound in a Multilevel Model?* Presented at [International Meeting of the Psychometric Society 2025](https://www.psychometricsociety.org/imps-2025). [Slides](pdf/IMPS_2025_MTruong_July_11_2025.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [Program](pdf/imps-2025-final-program.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [Abstract](pdf/imps2025-abstracts.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"}

-   Truong MS. & Choi JY. (2024) Talk: *Machine Learning Structural Equation Modeling and Falsificatory Data Analysis.* Presented at [Canadian Psychological Association 2024](https://cpa.ca/docs/File/Convention/2024/Abstract%20Book%202024-v1.2.pdf) and [Modern Modeling Methods 2024](https://modeling.uconn.edu/mmm-2024-archive/). [Slides](pdf/MMM2024%20Talk.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [MMM Program](pdf/M3_2024_Program_06-24-2024.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [CPA Program](pdf/CPA_Abstract%20Book%202024-v1.2.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"}

-   Truong MS., Crone G., Alter, U., & Choi JY. (2024) Poster: *Planting Decision Trees: Human-Friendly Interpretation of Monte Carlo Simulations, Multiverse Analyses and Multivariate Posterior Distributions.* Presented at [Canadian Psychological Association 2024](https://cpa.ca/docs/File/Convention/2024/Abstract%20Book%202024-v1.2.pdf) and [Modern Modeling Methods 2024](https://modeling.uconn.edu/mmm-2024-archive/). [Poster](pdf/CPA_MMM_2024_Poster.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [MMM Program](pdf/M3_2024_Program_06-24-2024.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"} [CPA Program](pdf/CPA_Abstract%20Book%202024-v1.2.pdf){.btn .btn-outline-primary .btn .btn-page-header .btn-xs role="button"}
