---
title: "Quotes I Appreciate"
date: "2026-01-05"
draft: FALSE
categories: [quotes]
license: ""
---

# Direct Quotes

1.  Experience is the name we give to our mistakes. \~ [Oscar Wilde](https://www.goodreads.com/quotes/8406509-experience-is-the-name-we-give-to-our-mistakes)
2.  I would prefer even to fail with honor than to win by cheating. \~ [Sophocles](https://www.goodreads.com/quotes/10921404-i-would-prefer-even-to-fail-with-honor-than-to)

# Paraphrased with Source Amnesia

1.  People will remember the way you make them feel, not what you remember doing for them.

2.  In any single large organizations or social group, different parts of the group will inevitably come into conflict with and contradict each other.

3.  In complex systems, such as large social groups and people's personal psychological life, there are no actions or policies that are good without qualification. Unintended consequences abound.

4.  Honesty without compassion is brutality. Kindness without honesty is manipulation.

5. Mathematics and philosophy are like exercise. I don't expect to outrun a car or even a bike, or to outlift a lever or a crane, but exercise is still important. 